name: docker-trino

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build_x86:
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest x86
    steps:
      - name: checkout repo
      - uses: actions/checkout@v3
      - name: Build for x86
        run: make build
  
  Build_Arm64v7:
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 armv7
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Build on ubuntu-20.04 armv7
        with:
          arch: armv7
          distro: ubuntu20.04
          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            make arm64v8
