name: docker-trino

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build_x86:
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest x86
    steps:
      - name: checkout repo
      - uses: actions/checkout@v3
      - name: Build for x86
        run: make build
  Build_Arm64v7:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-20.04 armv7
    steps:
      - name: checkout repo
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        id: build
        with:
          arch: armv7
          distro: ubuntu20.04
          # Set an output parameter `uname` for use in subsequent steps
          run: make arm64v8