name: docker-trino

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build_x86:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v3
      - name: Build for x86
        run: make build
  Build_Arm64v8:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v3
      - name: Build for arm64v8
        with:
          arch: arm64v8
        run: make arm64v8