name: "build images"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub 
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      -
        name: Build
        run: |
          make build
      - 
        name: Test
        run: |
          make test

      
