name: "build images"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        env: # Or as an environment variable
          super_secret: ${{ secrets.SuperSecret }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          password: ${{ secrets.DOCKER_HUB_USERNAME }}
      -
        name: Build
        run: |
          make build
      - 
        name: Test
        run: |
          make test

      
